const nodemailer = require("nodemailer");
const Mailgen = require("mailgen");
const bcrypt = require('bcrypt');

const sendMail = async (email, token) => {
    // Extracting name and email from request body
    // Rename email variable to userEmail

    // Create a nodemailer transporter
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: 'hunugupta1@gmail.com', // Gmail account used for sending emails
        pass: 'wjmlzrkqpjxprmvu', // Password for the Gmail account
      }
    });

    // Create a Mailgen instance for generating HTML email content
    const mailGenerator = new Mailgen({
      theme: "salted", // Specify the theme for the email (can be customized)
      product: {
        name: "Your App", // Name of your application
        link: "https://yourapp.com/" // Link to your application
      }
    });

    // Define the content structure of the email
    const emailContent = {
      body: {
        name:   `${email}`, // Use provided name or default to "User"
        intro: "hello", // Introduction text of the email
        action: {
          instructions: "To express my regret, please click the link below:", // Instructions for the action
          button: {
            color: "#FF3838", // Color of the button
            text: "forget password", // Text displayed on the button
           // link: `http://localhost:/resetPassword?token=${token}`// Link the button directs to
           link: `http://localhost:7070/resetPassword?token=${token}`// Link the button directs to

          }
        },
        outro: "If you have any further concerns or questions, feel free to reply to this email. I appreciate your understanding." // Closing text of the email
      }
    };

    // Generate the HTML content of the email using Mailgen
    const emailBody = mailGenerator.generate(emailContent);

    // Send the email using nodemailer transporter  
    let info = await transporter.sendMail({
      from: 'shrikanttechies111223@gmail.com', // Sender information
      to:  email, // Recipient's email address
      subject: "forget password", // Subject of the email
      text: "task", // Plain text version of the email
      html: emailBody, // HTML version of the email generated by Mailgen
    });

  
  
};

module.exports = sendMail; // Export sendMail function for use in other modules



